Add rule to check GKE service accounts for `container.defaultNodeServiceAccount` permissions
GoogleCloudPlatform/gcpdiag pull request #105
Opened 2024-11-26 11:12 UTC by m3adow

Also, fix smaller typos I found randomly.

Closes #102

2025-01-09 16:27 UTC, eugenenuke requested changes
Hey, thanks for contributing to the project

Everything looks good, just a couple of small issues.

2025-01-09 16:27 UTC, eugenenuke commented on website/content/en/rules/gke/ERR/2024_003.md
> +  GKE nodes service account permissions fit container.defaultNodeServiceAccount role :-)
pls, remove the 3 chars at the end of the line :)

2025-01-09 16:27 UTC, eugenenuke commented on bin/gcpdiag
It's better to separate independent changes, otherwise it'll make any roll back a tricky task

2025-01-09 16:27 UTC, eugenenuke commented on gcpdiag/lint/gce/err_2024_003_vm_secure_boot_failures.py
same: It's better to separate independent changes, otherwise it'll make any roll back a tricky task

2025-01-09 16:32 UTC, eugenenuke reviewed
I think with this change we can also deprecate (delete) these two:
- gcpdiag/lint/gke/err_2021_001_logging_perm.py
- gcpdiag/lint/gke/err_2021_002_monitoring_perm.py

2025-01-22 12:47 UTC, m3adow commented on bin/gcpdiag
Moved to #107

2025-01-22 12:47 UTC, m3adow commented on gcpdiag/lint/gce/err_2024_003_vm_secure_boot_failures.py
Moved to #107

2025-01-22 12:52 UTC, m3adow commented on gcpdiag/lint/gke/err_2024_003_default_node_serviceaccount_perm.py
> +        if not iam.is_service_account_enabled(sa, context.project_id):
We still have to check to have a proper error message otherwise, no?

2025-01-22 13:08 UTC, m3adow commented
Thanks for your review, @eugenenuke. I'm afraid I will need some help with the tests though.

2025-01-22 13:53 UTC, eugenenuke commented on gcpdiag/lint/gke/err_2024_003_default_node_serviceaccount_perm.py
> +        if not iam.is_service_account_enabled(sa, context.project_id):
No,  I don't think we need it here:

1.  The rule name suggests it's checking permissions only 
2.  I don't think we need to warn the user twice, `err_2021_012` will highlight the problem, let's not combine multiple checks into one (easier to explain how to mitigate in a separate rule)

2025-01-22 14:17 UTC, eugenenuke commented
> I'm afraid I will need some help with the tests though.

Both tests failed due to lack of a test snapshot:

- `run "make snapshots" to generate rule snapshot: gcpdiag/lint/gke/snapshots/ERR_2024_003.txt`
- `FAILED gcpdiag/lint/gke/gke_rules_snapshot_test.py::Test::test_all_rules`

As the output suggests, you need to run "make snapshots" command from the repo root directory, add the generated file(s) and push the changes

2025-01-23 08:07 UTC, m3adow commented
> As the output suggests, you need to run "make snapshots" command from the repo root directory, add the generated file(s) and push the changes

I tried that already, but `make snapshots` also fails:

<details>


```
==================================================================== FAILURES =====================================================================
_______________________________________________________________ Test.test_all_rules _______________________________________________________________
name = 'roles/container.defaultNodeServiceAccount', api_project_id = 'gcpdiag-gke1-aaaa'

    @caching.cached_api_call(expire=config.STATIC_DOCUMENTS_EXPIRY_SECONDS)
    def _get_predefined_role(name: str, api_project_id: str) -> Role:
      """Returns a predefined role using roles.get
    
      It should only be used if role is internal and cannot be retrieved using
      roles.list. For all other roles, _get_predefined_roles should be preferred
      because of caching efficiency
      """
      logging.info('fetching IAM role \'%s\'', name)
      iam_api = apis.get_api('iam', 'v1', api_project_id)
      request = iam_api.roles().get(name=name)
    
      try:
>       response = request.execute(num_retries=config.API_RETRIES)

gcpdiag/queries/iam.py:110: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <gcpdiag.queries.iam_stub.IamApiStub object at 0x7e192567fd90>, num_retries = 3

    def execute(self, num_retries=0):
      if self.mock_state == 'roles':
        # Predefined roles don't depend on a project, always using dump in `gke1`
        json_dir = PREFIX_GKE1
      elif self.project_id:
        json_dir = apis_stub.get_json_dir(self.project_id)
      elif self.api_project_id:
        json_dir = apis_stub.get_json_dir(self.api_project_id)
      else:
        json_dir = PREFIX_GKE1
    
      if self.mock_state == 'serviceaccounts_get':
        service_accounts_filename = json_dir / 'iam-service-accounts.json'
        with open(service_accounts_filename, encoding='utf-8') as json_file:
          service_accounts_data = json.load(json_file)
          service_accounts = {
              sa['email']: sa for sa in service_accounts_data['accounts']
          }
          if self.argument in service_accounts:
            return service_accounts[self.argument]
          else:
            raise googleapiclient.errors.HttpError(
                httplib2.Response({'status': 404}), b'not found')
      elif self.mock_state == 'serviceaccounts_getIamPolicy':
        json_filename = json_dir / 'iam-service-account-policy.json'
        with open(json_filename, encoding='utf-8') as json_file:
          return json.load(json_file)
      elif self.mock_state == 'serviceaccounts':
        json_filename = json_dir / 'iam-service-accounts.json'
        with open(json_filename, encoding='utf-8') as json_file:
          return json.load(json_file)
      elif self.mock_state == 'roles_get':
        json_filename = json_dir / 'iam-roles-get.json'
        with open(json_filename, encoding='utf-8') as json_file:
          roles_data = json.load(json_file)
          roles = {role['name']: role for role in roles_data['roles']}
          if self.argument in roles:
            return roles[self.argument]
          else:
>           raise googleapiclient.errors.HttpError(
                httplib2.Response({'status': 404}), b'not found')
E           googleapiclient.errors.HttpError: <HttpError 404 when requesting None returned "Ok". Details: "not found">

gcpdiag/queries/iam_stub.py:167: HttpError

The above exception was the direct cause of the following exception:

self = <gcpdiag.lint.gke.gke_rules_snapshot_test.Test object at 0x7e1926001960>
snapshot = <pytest_snapshot.plugin.Snapshot object at 0x7e1925f32c50>

    def test_all_rules(self, snapshot):
      for rule in self._list_rules():
        snapshot.snapshot_dir = path.join(path.dirname(self.rule_pkg.__file__),
                                          'snapshots')
        repo = self._mk_repo(rule)
        output_stream = io.StringIO()
        repo.result.add_result_handler(
            self._mk_output(output_stream).result_handler)
>       repo.run_rules(self._mk_context())

gcpdiag/lint/snapshot_test_base.py:48: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
gcpdiag/lint/__init__.py:512: in run_rules
    self.execution_strategy.run_rules(context, self.result, rules_to_run)
gcpdiag/lint/__init__.py:621: in run_rules
    rule.run_rule_f(context, rule_report)
gcpdiag/lint/gke/err_2024_003_default_node_serviceaccount_perm.py:51: in run_rule
    elif not iam_policy.has_role_permissions(f'serviceAccount:{sa}', ROLE):
gcpdiag/queries/iam.py:397: in has_role_permissions
    p for p in _get_iam_role(role, self.project_id).permissions
gcpdiag/queries/iam.py:146: in _get_iam_role
    return _get_predefined_role(name, default_project_id)
gcpdiag/caching.py:218: in _cached_api_call_wrapper
    result = func(*args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

name = 'roles/container.defaultNodeServiceAccount', api_project_id = 'gcpdiag-gke1-aaaa'

    @caching.cached_api_call(expire=config.STATIC_DOCUMENTS_EXPIRY_SECONDS)
    def _get_predefined_role(name: str, api_project_id: str) -> Role:
      """Returns a predefined role using roles.get
    
      It should only be used if role is internal and cannot be retrieved using
      roles.list. For all other roles, _get_predefined_roles should be preferred
      because of caching efficiency
      """
      logging.info('fetching IAM role \'%s\'', name)
      iam_api = apis.get_api('iam', 'v1', api_project_id)
      request = iam_api.roles().get(name=name)
    
      try:
        response = request.execute(num_retries=config.API_RETRIES)
      except googleapiclient.errors.HttpError as err:
        if err.resp.status == 404:
>         raise RoleNotFoundError(f'unknown role: {name}') from err
E         gcpdiag.queries.iam.RoleNotFoundError: unknown role: roles/container.defaultNodeServiceAccount

gcpdiag/queries/iam.py:113: RoleNotFoundError
---------------------------------------------------------------- Captured log call ----------------------------------------------------------------
WARNING  root:kubectl.py:142 Authentication failed for cluster gcpdiag-gke1-aaaa/europe-west4/autopilot-gke2
WARNING  root:kubectl.py:142 Authentication failed for cluster gcpdiag-gke1-aaaa/europe-west4/gke2
WARNING  root:kubectl.py:142 Authentication failed for cluster gcpdiag-gke1-aaaa/europe-west4/gke3
WARNING  root:kubectl.py:142 Authentication failed for cluster gcpdiag-gke1-aaaa/europe-west4-a/gke1
WARNING  root:kubectl.py:142 Authentication failed for cluster gcpdiag-gke1-aaaa/europe-west4-a/gke4
WARNING  root:kubectl.py:142 Authentication failed for cluster gcpdiag-gke1-aaaa/europe-west4-a/gke6
============================================================= short test summary info =============================================================
FAILED gcpdiag/lint/gke/gke_rules_snapshot_test.py::Test::test_all_rules
========================================================= 1 failed, 490 passed in 23.04s ==========================================================
make: *** [Makefile:22: snapshots] Error 1
```


</details>


I assume I have to define the role in the mock tests somewhere, but where and how? There's no documentation for such case.

2025-02-10 16:29 UTC, eugenenuke commented
Yeah, unfortunately we don't have it covered in documentation yet.

Still, it's open source.

Some hints in the output could help to identify the starting point and trace it. The module that fails (make snapshots) calls purest, and its "snapshot" feature in particular, see https://github.com/joseph-roitman/pytest-snapshot

``` err_2024_003_default_node_serviceaccount_perm.py:51: in run_rule
    elif not iam_policy.has_role_permissions(f'serviceAccount:{sa}', ROLE):
../../queries/iam.py:397: in has_role_permissions
    p for p in _get_iam_role(role, self.project_id).permissions
../../queries/iam.py:146: in _get_iam_role
    return _get_predefined_role(name, default_project_id)
```

queries/iam.py -> queries/iam_test.py -> queries/iam_stub.py -> "PREFIX_GKE1 = pathlib.Path(__file__).parents[2] / 'test-data/gke1/json-dumps'" -> test-data/gke1/Makefile, line 172 ("json-dumps/iam-roles-get.json:")


Here's the full git-diff for the current state of your commit that makes it pass the checks:  ```
diff --git a/test-data/gke1/Makefile b/test-data/gke1/Makefile
index 6eb2cfc28..5a40a86f9 100644
--- a/test-data/gke1/Makefile
+++ b/test-data/gke1/Makefile
@@ -173,7 +173,13 @@ json-dumps/iam-roles-get.json:
 	$(CURL) -fsS \
 		'https://iam.googleapis.com/v1/roles/container.nodeServiceAgent' \
 		| $(SED_SUBST_FAKE) \
-		| jq '{"roles": [.]}' >$@
+		| jq '{"roles": [.]}' >$@.tmp
+	$(CURL) -fsS \
+		'https://iam.googleapis.com/v1/roles/container.defaultNodeServiceAccount' \
+		| $(SED_SUBST_FAKE) \
+		| jq '{"roles": [.]}' >>$@.tmp
+	jq -s '. | {"roles": map(.)}' $@.tmp > $@
+	rm $@.tmp
 
 json-dumps/iam-service-accounts.json:
 	$(CURL) -fsS \
diff --git a/test-data/gke1/json-dumps/iam-roles-get.json b/test-data/gke1/json-dumps/iam-roles-get.json
index 1b4e88437..95e259c8d 100644
--- a/test-data/gke1/json-dumps/iam-roles-get.json
+++ b/test-data/gke1/json-dumps/iam-roles-get.json
@@ -2,7 +2,7 @@
   "roles": [
     {
       "name": "roles/container.nodeServiceAgent",
-      "title": "Kubernetes Engine Node Service Agent",
+      "title": "[Deprecated] Kubernetes Engine Node Service Agent",
       "description": "Minimal set of permission required by a GKE node to support standard capabilities such as logging and monitoring export, and image pulls.",
       "includedPermissions": [
         "autoscaling.sites.writeMetrics",
@@ -10,11 +10,29 @@
         "monitoring.metricDescriptors.create",
         "monitoring.metricDescriptors.list",
         "monitoring.timeSeries.create",
+        "monitoring.timeSeries.list",
         "resourcemanager.projects.get",
         "resourcemanager.projects.list",
+        "serviceusage.services.use",
         "storage.objects.get",
         "storage.objects.list"
       ],
+      "stage": "GA",
+      "etag": "AA=="
+    },
+    {
+      "name": "roles/container.defaultNodeServiceAccount",
+      "title": "Kubernetes Engine Default Node Service Account",
+      "description": "Least privilege role to use as the default service account for GKE Nodes.",
+      "includedPermissions": [
+        "autoscaling.sites.writeMetrics",
+        "logging.logEntries.create",
+        "monitoring.metricDescriptors.create",
+        "monitoring.metricDescriptors.list",
+        "monitoring.timeSeries.create",
+        "monitoring.timeSeries.list"
+      ],
+      "stage": "GA",
       "etag": "AA=="
     }
   ]
 ```

2025-02-14 07:57 UTC, m3adow commented on gcpdiag/lint/gke/err_2024_003_default_node_serviceaccount_perm.py
> +        if not iam.is_service_account_enabled(sa, context.project_id):
Fixed.

2025-02-14 08:00 UTC, m3adow commented
Thanks for your help, @eugenenuke. I think I got it now.

2025-02-14 13:17 UTC, eugenenuke approved these changes
LGTM

2025-02-14 13:29 UTC, merged